name: netguard
description: "A powerful HTTP client for Flutter built on top of Dio with enhanced security and networking capabilities."
version: 1.0.0
homepage: https://github.com/nitesh695/NetGuard
repository: https://github.com/nitesh695/NetGuard
issue_tracker: https://github.com/nitesh695/NetGuard/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.0
  build_runner: ^2.4.7

flutter:

